In [1]:
import pandas as pd

DESAFIO 1 - Normalizando Vendas online e Locação Imóveis.

In [2]:
dados_vendas = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Pandas: transformação e manipulação de dados/dados_vendas_clientes.json')
dados_locacao = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Pandas: transformação e manipulação de dados/dados_locacao_imoveis.json')

In [3]:
dados_locacao = pd.json_normalize(dados_locacao['dados_locacao'])
dados_locacao.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [4]:
dados_vendas = pd.json_normalize(dados_vendas['dados_vendas'])
dados_vendas.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

# Exercício

In [5]:
df['quantidade'] = df['quantidade'].apply(lambda x: x.replace(' pessoas', '').replace(' pessoa', ''))
df['salario'] = df['salario'].apply(lambda x: x.replace('$', '').replace(' reais', '').replace('.',''))

NameError: name 'df' is not defined

In [ ]:
df['quantidade'] = df['quantidade'].astype(np.int64)
df['salario'] = df['salario'].astype(np.float64)

In [ ]:
df.info()

In [ ]:
import pandas as pd
import numpy as np

# dados da firma
dados = {
    'cargo': ['Gerencia', 'Coordenação', 'Supervisão', 'Analista', 'Assistente', 'Operação', 'Auxiliar', 'Estágio', 'Assessoria', 'Consultoria'],
    'quantidade': ['2 pessoas', '1 pessoa', '3 pessoas', '4 pessoas', '5 pessoas', '3 pessoas', '2 pessoas', '1 pessoa', '1 pessoa', '1 pessoa'],
    'salario': ['$10.000 reais', '$8.000 reais', '$7.000 reais', '$5.000 reais', '$4.000 reais', '$3.500 reais', '$3.000 reais', '$1.500 reais', '$2.500 reais', '$6.000 reais']
}

# transformando o dicionário em DataFrame
df = pd.DataFrame(dados)

# df é o DataFrame com os dados da firma
df

#Desafio 2

In [6]:
colunas_vendas= list(dados_vendas.columns)
colunas_vendas

['Data de venda', 'Cliente', 'Valor da compra']

In [7]:
dados_vendas = dados_vendas.explode(colunas_vendas[1:])
dados_vendas.reset_index(drop=True, inplace=True)
dados_vendas

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [8]:
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [9]:
# Iniciar a transformação
# Import da biblioteca numpy
import numpy as np
# Remover os textos presentes na base
# Trocar as vírgulas separadoras do decimal por ponto
dados_vendas['Valor da compra'] = dados_vendas['Valor da compra'].astype(str).apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())
# Alterar os tipo de dado para float
dados_vendas['Valor da compra'] = dados_vendas['Valor da compra'].astype(np.float64)
# Verificar a transformação
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [10]:
dados_locacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 15 non-null     object
 1   datas_combinadas_pagamento  15 non-null     object
 2   datas_de_pagamento          15 non-null     object
 3   valor_aluguel               15 non-null     object
dtypes: object(4)
memory usage: 612.0+ bytes

In [11]:
colunas_locacao = list(dados_locacao.columns)
colunas_locacao

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [12]:
dados_locacao = dados_locacao.explode(colunas_locacao[1:])

In [13]:
dados_locacao.reset_index(drop=True,inplace=True)

In [14]:
dados_locacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [15]:
dados_locacao['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [16]:
# Iniciar a transformação
# Import da biblioteca numpy
import numpy as np

In [17]:
# Remover os textos presentes na base
# Trocar as vírgulas separadoras do decimal por ponto
dados_locacao['valor_aluguel'] = dados_locacao['valor_aluguel'].astype(str).apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
# Alterar os tipo de dado para float
dados_locacao['valor_aluguel'] = dados_locacao['valor_aluguel'].astype(np.float64)
# Verificar a transformação
dados_locacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

### DESAFIO 3 - transformando strings

In [18]:
dados_vendas['Cliente'].head()

0       @ANA _LUCIA 321
1    DieGO ARMANDIU 210
2    DieGO ARMANDIU 210
3    DieGO ARMANDIU 210
4    Isabely JOanes 738
Name: Cliente, dtype: object

In [19]:
dados_vendas['Cliente'] = dados_vendas['Cliente'].str.lower()

In [20]:
dados_vendas['Cliente'] = dados_vendas['Cliente'].str.replace('[^a-z ]', '', regex=True).str.strip()

In [21]:
dados_vendas['Cliente'].head()

0         ana lucia
1    diego armandiu
2    diego armandiu
3    diego armandiu
4    isabely joanes
Name: Cliente, dtype: object

In [22]:
dados_locacao['apartamento'].head()

0    A101 (blocoAP)
1    A101 (blocoAP)
2    A102 (blocoAP)
3    A102 (blocoAP)
4    B201 (blocoAP)
Name: apartamento, dtype: object

In [23]:
dados_locacao['apartamento'] = dados_locacao['apartamento'].str.lower()

In [24]:
dados_locacao['apartamento'] = dados_locacao['apartamento'].str.replace(' \(blocoap\)', '', regex=True).str.strip()

In [25]:
dados_locacao['apartamento'].head()

0    a101
1    a101
2    a102
3    a102
4    b201
Name: apartamento, dtype: object

### DESAFIO 4 - Datetime

In [29]:
import datetime as dt
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados_vendas['Data de venda'] = pd.to_datetime(dados_vendas['Data de venda'], format='%d/%m/%Y')
# Visualizar o resultado
dados_vendas

# Verificar o resultado da transformação
dados_vendas.info()

# Calcular o total arrecadado em compras por cada cliente
total_compras = dados_vendas.groupby(['Cliente'])['Valor da compra'].sum()
# Visualizar o resultado
total_compras

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

Cliente
ana lucia          836.50
diego armandiu    1478.47
isabely joanes    2329.30
joo gabriel        386.34
julya meireles    1643.74
maria julia       2086.65
paulo castro       899.16
pedro pasco        311.15
thiago fritzz      885.24
Name: Valor da compra, dtype: float64

In [27]:
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados_locacao['datas_combinadas_pagamento'] = pd.to_datetime(dados_locacao['datas_combinadas_pagamento'], format='%d/%m/%Y')
dados_locacao['datas_de_pagamento'] = pd.to_datetime(dados_locacao['datas_de_pagamento'], format='%d/%m/%Y')

# Visualizar o resultado
dados_locacao

# Para contribuir na solução do contexto é possível calcular a diferença de dias
# entre a data combinada e a data de pagamento com dt.days
dados_locacao['atraso'] = (dados_locacao['datas_de_pagamento'] - dados_locacao['datas_combinadas_pagamento']).dt.days

# Observar o novo DataFrame
dados_locacao

# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados_locacao.groupby(['apartamento'])['atraso'].mean()

# Visualizar o resultado
media_atraso

apartamento
a101    3.0
a102    2.0
b201    2.0
b202    2.0
c301    4.5
c302    4.0
d401    1.0
d402    4.0
e501    0.5
e502    4.0
f601    4.0
f602    1.5
g701    6.5
g702    2.0
h801    2.0
Name: atraso, dtype: float64