### DESAFIO 1

In [ ]:
import json
import pandas as pd

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/limpeza e tratamento de dados/informacoes.json') as f:
  dados = json.load(f)

In [ ]:
#Tarefa Json_Normalize
import pandas as pd
import json
data ={
  "nome": "João",
  "idade": 28,
  "enderecos": [
    {
      "tipo": "casa",
      "rua": "Rua A",
      "numero": 123,
      "cidade": "São Paulo"
    },
    {
      "tipo": "trabalho",
      "rua": "Rua B",
      "numero": 456,
      "cidade": "Rio de Janeiro"
    }
  ]
}
df=pd.json_normalize(data, record_path="enderecos", meta=["nome", "idade"])
print(df)

       tipo    rua  numero          cidade  nome idade
0      casa  Rua A     123       São Paulo  João    28
1  trabalho  Rua B     456  Rio de Janeiro  João    28

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tipo    2 non-null      object
 1   rua     2 non-null      object
 2   numero  2 non-null      int64
 3   cidade  2 non-null      object
 4   nome    2 non-null      object
 5   idade   2 non-null      object
dtypes: int64(1), object(5)
memory usage: 228.0+ bytes

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### DESAFIO 3

In [7]:
# Importando as bibliotecas necessárias
import pandas as pd
import json

# carrega o conjunto de dados
with open('/content/drive/MyDrive/Colab Notebooks/limpeza e tratamento de dados/cursos_cadastrados.json', 'r') as f:
    data = json.load(f)

# normaliza o json
df = pd.json_normalize(data)

# exibe o DataFrame resultante
print(df)

                             curso      categoria carga_horaria concluintes  \
0         Introdução à programação    Programação      20 horas         100
1            Excel para iniciantes  Produtividade          None        None
2  Marketing digital para negócios      Marketing      30 horas          75
3          Inteligência artificial    Programação      40 horas
4             Inglês para negócios        Idiomas      20 horas          30
5         Introdução à programação    Programação      20 horas         100

  data_inicio data_conclusao  \
0  2022-01-01     2022-01-20
1        None           None
2  2022-03-01     2022-03-31
3  2022-04-01
4
5  2022-01-01     2022-01-20

                                           descricao  preco  instrutor.nome  \
0        Curso introdutório à programação com Python  99.90      João Silva
1                                               None   None  Maria Oliveira
2                    Curso introdutório em marketing   89.9      Ana Santos
3  Curso avançado sobre inteligência artificial c...  129.9
4                      Curso de inglês para negócios   69.9      John Smith
5        Curso introdutório à programação com Python  99.90      João Silva

                     instrutor.email instrutor.telefone
0      joao.silva@emailaleatorio.com     (11) 9999-9999
1  maria.oliveira@emailaleatorio.com     (11) 8888-8888
2      ana.santos@emailaleatorio.com     (11) 7777-7777
3         contato@emailaleatorio.com
4
5      joao.silva@emailaleatorio.com     (11) 9999-9999

In [8]:
df.isnull().sum().sum()

6

In [9]:
df[df.isna().any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
1,Excel para iniciantes,Produtividade,None,None,None,None,None,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888

In [10]:
df.dropna(inplace=True)

In [11]:
df.duplicated()

0    False
2    False
3    False
4    False
5     True
dtype: bool

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df[df['instrutor.nome'] == ""]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,

In [14]:
df[df['data_conclusao'] == ""]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,

In [15]:
# Substitui strings vazias por valores nulos
df.replace('', pd.NA, inplace=True)

In [16]:
df.dropna(inplace=True)
print(df)

                             curso    categoria carga_horaria concluintes  \
0         Introdução à programação  Programação      20 horas         100
2  Marketing digital para negócios    Marketing      30 horas          75

  data_inicio data_conclusao                                    descricao  \
0  2022-01-01     2022-01-20  Curso introdutório à programação com Python
2  2022-03-01     2022-03-31              Curso introdutório em marketing

   preco instrutor.nome                instrutor.email instrutor.telefone
0  99.90     João Silva  joao.silva@emailaleatorio.com     (11) 9999-9999
2   89.9     Ana Santos  ana.santos@emailaleatorio.com     (11) 7777-7777

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      object
 4   data_inicio         2 non-null      object
 5   data_conclusao      2 non-null      object
 6   descricao           2 non-null      object
 7   preco               2 non-null      object
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: object(11)
memory usage: 192.0+ bytes

In [18]:
# Converte a concluintes para o tipo inteiro
df['concluintes'] = df['concluintes'].astype(int)

# Converte a coluna data_inicio e data_conclusao para o tipo datetime
df['data_inicio'] = pd.to_datetime(df['data_inicio'])
df['data_conclusao'] = pd.to_datetime(df['data_conclusao'])

# Convertendo a coluna preço para o tipo float
df['preco'] = df['preco'].astype(float)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      int64
 4   data_inicio         2 non-null      datetime64[ns]
 5   data_conclusao      2 non-null      datetime64[ns]
 6   descricao           2 non-null      object
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: datetime64[ns](2), float64(1), int64(1), object(7)
memory usage: 192.0+ bytes

### DESAFIO 4

In [20]:
import pandas as pd

# criando um DataFrame com 30 transações aleatórias
df = pd.DataFrame({
    'ID da transação': range(1, 31),
    'Valor da transação': [100, 200, 150, 500, 300, 913, 250, 400, 200, 150,
                           200, 200, 400, 300, 150, 301, 805, 300, 400, 250,
                           150, 100, 500, 600, 200, 350, 100, 250, 800, 250],
    'Data da transação': pd.date_range(start='2022-01-01', end='2022-01-30', freq='D'),
    'Local da transação': ['São Paulo, Brasil', 'Rio de Janeiro, Brasil', 'Belo Horizonte, Brasil', 'São Paulo, Brasil',
                           'São Paulo, Brasil', 'Nova Iorque, EUA', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil',
                           'Rio de Janeiro, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil',
                           'São Paulo, Brasil', 'São Paulo, Brasil', 'Los Angeles, EUA', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil',
                           'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil', 'São Paulo, Brasil',
                           'São Paulo, Brasil', 'São Paulo, Brasil', 'Miami, EUA', 'São Paulo, Brasil']
})

In [21]:
def calc_outliers(column, dataframe):

  # calculando o IQR e definindo o limite para outliers
  Q1 = dataframe[column].quantile(0.25)
  Q3 = dataframe[column].quantile(0.75)
  IQR = Q3 - Q1
  limite_inferior = Q1 - 1.5 * IQR
  limite_superior = Q3 + 1.5 * IQR

  # identificando os outliers
  outliers = dataframe[(dataframe[column] < limite_inferior) | (dataframe[column] > limite_superior)]

  # retornando os outliers
  return outliers

In [24]:
print(calc_outliers('Valor da transação', df))

    ID da transação  Valor da transação Data da transação Local da transação
5                 6                 913        2022-01-06   Nova Iorque, EUA
16               17                 805        2022-01-17   Los Angeles, EUA
28               29                 800        2022-01-29         Miami, EUA